version: "3.9"
services:
  clanbotjukebox:
    container_name: clanbotjukebox
    image: clanbadjas/clanbotjukebox:latest
    env_file: .env
    restart: unless-stopped
    networks:
      - lavanet
    depends_on:
      - lavalink

  lavalink:
    container_name: clanbotjukebox-lava
    image: fredboat/lavalink:latest
    restart: unless-stopped
    expose:
      - 2333
    networks:
      - lavanet
    volumes:
      - /opt/discord/ClanBotJukebox/lavalink/application.yml:/opt/Lavalink/application.yml:ro

networks:
  lavanet:
